/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderOfProfessionRouteImport } from './routes/leader-of-profession'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DigitalHealthRouteImport } from './routes/digital-health'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AcademicRouteImport } from './routes/academic'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderOfProfessionRoute = LeaderOfProfessionRouteImport.update({
  id: '/leader-of-profession',
  path: '/leader-of-profession',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalHealthRoute = DigitalHealthRouteImport.update({
  id: '/digital-health',
  path: '/digital-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRoute = AcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/digital-health': typeof DigitalHealthRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRoute
  '/hospital': typeof HospitalRoute
  '/leader-of-profession': typeof LeaderOfProfessionRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/digital-health': typeof DigitalHealthRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRoute
  '/hospital': typeof HospitalRoute
  '/leader-of-profession': typeof LeaderOfProfessionRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/digital-health': typeof DigitalHealthRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRoute
  '/hospital': typeof HospitalRoute
  '/leader-of-profession': typeof LeaderOfProfessionRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic'
    | '/business'
    | '/contact'
    | '/digital-health'
    | '/education'
    | '/gallery'
    | '/hospital'
    | '/leader-of-profession'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic'
    | '/business'
    | '/contact'
    | '/digital-health'
    | '/education'
    | '/gallery'
    | '/hospital'
    | '/leader-of-profession'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic'
    | '/business'
    | '/contact'
    | '/digital-health'
    | '/education'
    | '/gallery'
    | '/hospital'
    | '/leader-of-profession'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicRoute: typeof AcademicRoute
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  DigitalHealthRoute: typeof DigitalHealthRoute
  EducationRoute: typeof EducationRoute
  GalleryRoute: typeof GalleryRoute
  HospitalRoute: typeof HospitalRoute
  LeaderOfProfessionRoute: typeof LeaderOfProfessionRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leader-of-profession': {
      id: '/leader-of-profession'
      path: '/leader-of-profession'
      fullPath: '/leader-of-profession'
      preLoaderRoute: typeof LeaderOfProfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-health': {
      id: '/digital-health'
      path: '/digital-health'
      fullPath: '/digital-health'
      preLoaderRoute: typeof DigitalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicRoute: AcademicRoute,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  DigitalHealthRoute: DigitalHealthRoute,
  EducationRoute: EducationRoute,
  GalleryRoute: GalleryRoute,
  HospitalRoute: HospitalRoute,
  LeaderOfProfessionRoute: LeaderOfProfessionRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
